---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moouaamm
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moouaamm
  template:
    metadata:
      labels:
        app: moouaamm
    spec:
      containers:
        - name: moouaamm
          image: wil42/playground:v2
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: moouaamm
  namespace: dev
spec:
  selector:
    app: moouaamm
  ports:
    - port: 8888
      targetPort: 8888
